export {default as Landing} from '../Landing/Landing'
export {default as SignIn} from '../Authentication/SignIn'
export {default as SignUp} from '../Authentication/SignUp'
export {default as Dashboard} from '../Dashboard/Dashboard'
export {default as ChatComponent} from '../ChatComponent/ChatComponent'